/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"


//==============================================================================
Fft_synth_oneAudioProcessorEditor::Fft_synth_oneAudioProcessorEditor (Fft_synth_oneAudioProcessor* ownerFilter)
    : AudioProcessorEditor (ownerFilter)
{
	panel = new GuiPanel(ownerFilter);
	addAndMakeVisible(panel);
	ownerFilter->setKeyboardState(panel->getKeyboardState());
    // This is where our plugin's editor size is set.
    setSize (600, 400);
}

Fft_synth_oneAudioProcessorEditor::~Fft_synth_oneAudioProcessorEditor()
{
}

//==============================================================================
void Fft_synth_oneAudioProcessorEditor::paint (Graphics& g)
{
    g.fillAll (Colours::white);
    g.setColour (Colours::black);
    g.setFont (15.0f);
    g.drawFittedText ("Hello World!",
                      0, 0, getWidth(), getHeight(),
                      Justification::centred, 1);
}
