/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_5F06103__
#define __PLUGINEDITOR_H_5F06103__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "GUI_Panel.h"

//==============================================================================
/**
*/
class Fft_synth_oneAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    Fft_synth_oneAudioProcessorEditor (Fft_synth_oneAudioProcessor* ownerFilter);
    ~Fft_synth_oneAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
	
	GuiPanel* panel;
};


#endif  // __PLUGINEDITOR_H_5F06103__
